### PR TITLE
Refactored Code by Mark Wasfy

### PR DESCRIPTION
**Pull request by MarkWasfy00**
### please tell me for any more modification !

### CODE REVIEW

**Comment by thisShouldNotBeWorking** [comment]
Great job !!!
There is just one problem. When you click on a hackathon or the participate now button it is supposed to redirect to the details page. But that doesn't seem to be working for some reason. Can you check on that?

**Comment by MarkWasfy00** [comment]
ok its done

**Comment by thisShouldNotBeWorking** [comment]
image

As you can see in the edit page the
1> Top yellow bar (make it responsive)
2> The medium level box ( allign the text verically center and increase font )
3> Edit and Delete button (make responsive and add colour)
seem off. Could you correct them too. You can refer the figma or ask me for any help

**Comment by MarkWasfy00** [comment]
I only worked on the home page thats what you asked for , maybe later but not now I would like you to accept my pull request

**Comment by thisShouldNotBeWorking** [comment]
okay thanks, great job

**Pull request merged**
